services:
  - type: web
    name: travela-laravel
    env: docker
    plan: free
    dockerfilePath: Dockerfile
    envVars:
      # Laravel config
      - key: APP_ENV
        value: "production"
      - key: APP_DEBUG
        value: "false"
      - key: APP_URL
        value: "https://travela.onrender.com"
      - key: APP_KEY
        value: "base64:881PY5d5inU6guy5ypiGssFL+M5ISGsqJVdZWC54CvA="

      # Database (Render MySQL)
      - key: DB_CONNECTION
        value: "mysql"
      - key: DB_HOST
        value: "db-abcdefg.render.com"
      - key: DB_PORT
        value: "3306"
      - key: DB_DATABASE
        value: "travela"
      - key: DB_USERNAME
        value: "admin"
      - key: DB_PASSWORD
        value: "12345678"

      # Mail (App Password Gmail)
      - key: MAIL_MAILER
        value: "smtp"
      - key: MAIL_HOST
        value: "smtp.gmail.com"
      - key: MAIL_PORT
        value: "587"
      - key: MAIL_USERNAME
        value: "nhoktin2809@gmail.com"
      - key: MAIL_PASSWORD
        value: "tuuloauuhoaiypzv"
      - key: MAIL_ENCRYPTION
        value: "tls"
      - key: MAIL_FROM_ADDRESS
        value: "nhoktin2809@gmail.com"
      - key: MAIL_FROM_NAME
        value: "Travela"

      # Google OAuth
      - key: GOOGLE_CLIENT_ID
        value: "799441907087-0vpi4l0k6d547gc2ubnfjaacu2b8rta4.apps.googleusercontent.com"
      - key: GOOGLE_CLIENT_SECRET
        value: "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"
      - key: GOOGLE_REDIRECT_URI
        value: "https://travela.onrender.com/auth/google/callback"

      # PayPal Sandbox
      - key: PAYPAL_MODE
        value: "sandbox"
      - key: PAYPAL_SANDBOX_CLIENT_ID
        value: "AW5zIj3lFCz3ozb8CNdConFYmKJ2bnFVO21BXWx6PEBwBY6piYktvhJIYP4-gBWb0KtuWYLQ_693ISKo"
      - key: PAYPAL_SANDBOX_CLIENT_SECRET
        value: "EMqXKObpee3oZm7E6lclONTnvQusV4gdVDe6yOgEQGTfrRIYbzE7ZfOOvXRJGLocVwpRpgJljxh5538E"
      - key: PAYPAL_CURRENCY
        value: "USD"
